# Generated by Django 2.2 on 2019-04-23 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('pwd', models.CharField(max_length=50)),
                ('nickname', models.CharField(max_length=20)),
            ],
        ),
    ]
